### ISSUE TITLE
Landing responsivo en cintillo de cajas.

### ISSUE THREAD

**Issue by memobuendia** [arturo1984/nuevo-home#4]
El cintillo se diseño para que se pege al lado derecho de la caja. Revisar el visual para que no se deforme en base a propuesta original. Ahora ni se ve centrado ni alineado a derecha. Si no se logra hacer que el cintillo no se deforme o se encime cuando se usa tableta por favor hacerlo del 100% del ancho de la caja.

![image](https://user-images.githubusercontent.com/20461757/40161237-ba5b9c4e-5975-11e8-8a37-917c42b8eca7.png)

**Comment by arturo1984** [comment]
ya esta el cintillo al 100%, creo que se ve mejor

**Comment by memobuendia** [comment]
Gracias cierro el issue.
