### ISSUE TITLE
Landing. Menú.

### ISSUE THREAD

**Issue by memobuendia** [arturo1984/nuevo-home#5]
Al dar click sobre la hamburguesa no se despliega el menú y marca errores en la consola. Por favor revisar en versión de chrome anexa.

![image](https://user-images.githubusercontent.com/20461757/40161409-4f4d8574-5976-11e8-95a2-afd723c3c79f.png)

![image](https://user-images.githubusercontent.com/20461757/40161439-6064ba62-5976-11e8-87ac-38f483ea8175.png)

**Comment by arturo1984** [comment]
creo que la version que descargaron esta fallando, nuestra version esta desplegandose bien el menu, nos podrias ayudar a reemplazar su version por la mas reciente de git.

gracias...

**Comment by arturo1984** [comment]
![image](https://user-images.githubusercontent.com/12704403/40189348-d556ed72-59c1-11e8-87c0-567991363854.png)

**Comment by memobuendia** [comment]
Ya se muestra correctamente. Gracias.
